---
- name: download
  become: yes
  become_user: root
  get_url:
    url: '{{ weave_url }}'
    dest: '{{ weave_install_exe }}'
    checksum: '{{ weave_checksum }}'
    mode: 0755
- name: link
  become: yes
  become_user: root
  file:
    src: '{{ weave_install_exe }}'
    dest: '{{ weave_link }}'
    state: link
