---
- name: downloading {{ weave_url }} to {{ weave_install_exe }}
  become: yes
  become_user: root
  get_url:
    url: '{{ weave_url }}'
    dest: '{{ weave_install_exe }}'
    checksum: '{{ weave_checksum }}'
    mode: 0755
- name: linking {{ weave_link }} to {{ weave_install_exe }}
  become: yes
  become_user: root
  file:
    src: '{{ weave_install_exe }}'
    dest: '{{ weave_link }}'
    state: link
